set_property SRC_FILE_INFO {cfile:/home/gursimran/Desktop/FPGA/Hello_World/Hello_World.srcs/constrs_1/new/const_oneHz_generator.xdc rfile:../../../Hello_World.srcs/constrs_1/new/const_oneHz_generator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports {clk_1Hz}]
